spring:
  application:
    name: BestShop
  datasource:
    url: jdbc:mysql://localhost:3306/bestshop?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 86400 #1d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
websiteUrl: http://localhost:8080